// ─── Solution Pages ───────────────────────────────────────────────────────────
export const solutionPages = [
  {
    path: "/solutions/mass-payouts",
    seo: { title: "Mass Payouts", desc: "Disburse payments to thousands simultaneously.", keywords: "mass payouts ACH SEPA SWIFT bulk payments platform" },
    tag: "SOLUTIONS", title: "Mass Payouts at Any Scale",
    subtitle: "Upload a single file and disburse payments to thousands simultaneously — across multiple payout methods and global payment networks.",
    features: [
      { icon: "Send",       title: "Bulk File Upload",      desc: "Upload CSV, Excel, or API batch — Paydex handles routing intelligently." },
      { icon: "Zap",        title: "Sub-second Processing", desc: "Each payment is validated, enriched, and routed in milliseconds." },
      { icon: "BarChart3",  title: "Live Tracking",         desc: "Monitor every payment in real time with granular status updates." },
      { icon: "Shield",     title: "Risk Screening",        desc: "Automated AML, sanctions, and fraud checks before payment release." },
      { icon: "RefreshCcw", title: "Auto-Retry Logic",      desc: "Failed payments are automatically retried on the next optimal rail." },
      { icon: "Globe",      title: "Global Coverage",       desc: "Send payroll, vendor payments, and bulk payouts across the United States and Europe with multi-currency support and intelligent routing." },
    ],
  },
  {
    path: "/solutions/invoice-payments",
    seo: { title: "Invoice Payments", desc: "Automate B2B invoice settlement.", keywords: "accounts payable automation ERP payments platform" },
    tag: "SOLUTIONS", title: "Automated Invoice Settlement",
    subtitle: "Connect your ERP and let Paydex handle matching, approval, and payment — end to end.",
    features: [
      { icon: "CreditCard",  title: "3-Way Matching",      desc: "PO, invoice, and receipt matching before any payment is released." },
      { icon: "CheckSquare", title: "Approval Workflows",  desc: "Configurable multi-level approvals with full audit trail." },
      { icon: "Link2",       title: "ERP Integration",     desc: "Syncs with SAP, Oracle, NetSuite, Microsoft Dynamics, and Workday." },
      { icon: "BarChart3",   title: "AP Analytics",        desc: "Track days payable outstanding, supplier performance, and payment trends." },
      { icon: "Globe",       title: "Multi-Currency",      desc: "Pay international suppliers in their local currency automatically." },
      { icon: "Shield",      title: "Duplicate Detection", desc: "Automated duplicate invoice blocking before payment." },
    ],
  },
  {
    path: "/solutions/payroll-disbursement",
    seo: { title: "Payroll Disbursement", desc: "Reliable multi-currency payroll disbursement.", keywords: "global payroll payments platform" },
    tag: "SOLUTIONS", title: "Payroll That Never Misses a Beat",
    subtitle: "Disburse salaries to employees and contractors across domestic and cross-border payment rails in the United States and Europe.",
    features: [
      { icon: "Users",       title: "Multi-Entity Payroll", desc: "Run payroll across subsidiaries and legal entities simultaneously." },
      { icon: "Globe",       title: "Cross-Border Pay",     desc: "Employees receive funds via ACH, SEPA, Digital Checks, Faster Payments, or SWIFT." },
      { icon: "Shield",      title: "Compliance Built-In",  desc: "Aligned with US, EU, and UK payroll compliance frameworks." },
      { icon: "CheckSquare", title: "Pay Slip Generation",  desc: "Automated payslips and payroll reports for finance teams." },
      { icon: "Zap",         title: "Scheduled Settlement", desc: "Ensure funds arrive exactly on scheduled payroll dates." },
      { icon: "BarChart3",   title: "Payroll Analytics",    desc: "Headcount cost, pay run history, and variance reporting." },
    ],
  },
  {
    path: "/solutions/vendor-payments",
    seo: { title: "Vendor Payments", desc: "Streamline supplier payment workflows.", keywords: "vendor payments supplier payments automation" },
    tag: "SOLUTIONS", title: "Vendor Payments, Simplified",
    subtitle: "Build stronger supplier relationships by paying faster, more accurately, and with full transparency.",
    features: [
      { icon: "Layers",      title: "Vendor Onboarding",       desc: "Collect bank details and KYB documentation through a secure portal." },
      { icon: "Shield",      title: "Vendor Verification",     desc: "Automated KYB verification and sanctions screening." },
      { icon: "CreditCard",  title: "Early Payment Discounts", desc: "Capture dynamic discounting opportunities automatically." },
      { icon: "Globe",       title: "International Vendors",   desc: "Pay suppliers globally via ACH, SEPA, Faster Payments, or SWIFT." },
      { icon: "BarChart3",   title: "Vendor Portal",           desc: "Suppliers track invoice and payment status through a self-service portal." },
      { icon: "RefreshCcw",  title: "Reconciliation",          desc: "Automatic matching of payments to invoices and purchase orders." },
    ],
  },
  {
    path: "/solutions/receivables-suite",
    seo: { title: "Receivables Suite", desc: "Accelerate cash collection and automate reconciliation.", keywords: "accounts receivable automation payments" },
    tag: "SOLUTIONS", title: "Get Paid Faster, Reconcile Instantly",
    subtitle: "Reduce DSO and close your books faster with intelligent receivables automation.",
    features: [
      { icon: "TrendingUp", title: "Smart Invoicing",          desc: "Generate, send, and track invoices across email and customer portals." },
      { icon: "RefreshCcw", title: "Auto-Reconciliation",      desc: "Payments automatically match to invoices as funds arrive." },
      { icon: "BarChart3",  title: "DSO Analytics",            desc: "Monitor days sales outstanding by customer, region, and product." },
      { icon: "PhoneCall",  title: "Collections Automation",   desc: "Automated reminders and follow-ups for overdue invoices." },
      { icon: "Globe",      title: "Multi-Rail Collection",    desc: "Accept payments via bank transfer, card networks, ACH, or SEPA." },
      { icon: "Shield",     title: "Fraud Prevention",         desc: "Payment authentication and chargeback protection on every transaction." },
    ],
  },
  {
    path: "/solutions/analytics-dashboard",
    seo: { title: "Analytics Dashboard", desc: "Real-time financial visibility across all payment flows.", keywords: "payment analytics treasury visibility" },
    tag: "SOLUTIONS", title: "Full Visibility. Zero Surprises.",
    subtitle: "A single pane of glass for every payment, every rail, every entity — updated in real time.",
    features: [
      { icon: "BarChart3",  title: "Real-Time Dashboard",      desc: "Live payment volumes, success rates, and FX exposure at a glance." },
      { icon: "Eye",        title: "Transaction Drill-Down",   desc: "Trace any payment from initiation to settlement instantly." },
      { icon: "TrendingUp", title: "Cash Flow Forecasting",    desc: "Predict inflows and outflows from scheduled and recurring payments." },
      { icon: "Globe",      title: "Multi-Currency Reporting", desc: "View financial performance across currencies and regions." },
      { icon: "Shield",     title: "Audit Trail",              desc: "Immutable log of approvals, actions, and payment events." },
      { icon: "Database",   title: "Custom Reports",           desc: "Build and export reports for finance, treasury, and compliance teams." },
    ],
  },
];

// ─── Who We Serve Pages ───────────────────────────────────────────────────────
export const servePages = [
  {
    path: "/who-we-serve/financial-institutions",
    seo: { title: "Financial Institutions", desc: "Payment infrastructure for banks, lenders, and fintechs.", keywords: "bank payments infrastructure fintech platform" },
    tag: "WHO WE SERVE", title: "Built for Financial Institutions",
    subtitle: "Whether you're a commercial bank, lender, or fintech — Paydex provides the rails to move money at scale.",
    features: [
      { icon: "Shield",    title: "Core Banking Integration", desc: "Connect Paydex to your core banking system via API or connectors." },
      { icon: "Globe",     title: "Interbank Settlement",     desc: "Integration with ACH, Fedwire, SEPA, and SWIFT networks." },
      { icon: "Lock",      title: "Regulatory Compliance",    desc: "Transaction monitoring aligned with US and EU financial regulations." },
      { icon: "BarChart3", title: "Disbursement Analytics",   desc: "Settlement reports, transaction monitoring, and reconciliation insights." },
      { icon: "Users",     title: "Beneficiary Management",   desc: "Manage verified payment recipients at enterprise scale." },
      { icon: "Cpu",       title: "White-Label Ready",        desc: "Embed Paydex infrastructure under your own brand." },
    ],
  },
  {
    path: "/who-we-serve/enterprises",
    seo: { title: "Enterprises", desc: "Enterprise payment infrastructure for complex global payables.", keywords: "enterprise treasury payments platform" },
    tag: "WHO WE SERVE", title: "Enterprise-Grade Disbursements",
    subtitle: "Complex multi-entity, multi-currency payables workflows — solved.",
    features: [
      { icon: "Layers",    title: "Multi-Entity Support",  desc: "Manage payables across subsidiaries and entities globally." },
      { icon: "Link2",     title: "ERP Integration",       desc: "Native connectors for SAP, Oracle, NetSuite, Workday, and Dynamics." },
      { icon: "Shield",    title: "Segregation of Duties", desc: "Role-based access controls with multi-level approvals." },
      { icon: "Globe",     title: "Global Treasury",       desc: "Centralised treasury visibility across regions and currencies." },
      { icon: "BarChart3", title: "Board-Level Reporting", desc: "Executive dashboards with spend analytics and financial insights." },
      { icon: "Lock",      title: "SSO and Audit",         desc: "SAML SSO, MFA, and immutable audit logs." },
    ],
  },
  {
    path: "/who-we-serve/mid-size-businesses",
    seo: { title: "Mid-Size Businesses", desc: "Enterprise payment capabilities without enterprise complexity.", keywords: "mid-market payments platform" },
    tag: "WHO WE SERVE", title: "Enterprise Power. Startup Speed.",
    subtitle: "Everything a growing company needs to run payments efficiently — without complexity.",
    features: [
      { icon: "Zap",       title: "Quick Onboarding",      desc: "Launch in days with guided onboarding and API setup." },
      { icon: "CreditCard",title: "Accounts Payable",      desc: "Automate supplier payments without implementing a full ERP." },
      { icon: "Users",     title: "Team Collaboration",    desc: "Finance and operations collaborate in one workflow." },
      { icon: "Globe",     title: "Cross-Border Payments", desc: "Pay suppliers and contractors globally." },
      { icon: "BarChart3", title: "Cash Flow Visibility",  desc: "Monitor obligations and balances in real time." },
      { icon: "Shield",    title: "Fraud Protection",      desc: "AI-powered risk scoring protects outbound payments." },
    ],
  },
  {
    path: "/who-we-serve/nonprofits",
    seo: { title: "Nonprofits", desc: "Grant disbursement and fund management tools for nonprofits.", keywords: "nonprofit payments platform" },
    tag: "WHO WE SERVE", title: "Payments Built for Impact",
    subtitle: "Disburse grants, salaries, and program funds with transparency and accountability.",
    features: [
      { icon: "HeartHandshake", title: "Grant Disbursement",   desc: "Release grant tranches with complete reporting." },
      { icon: "Shield",         title: "Donor Accountability", desc: "Transparent financial reporting for donors and boards." },
      { icon: "Globe",          title: "Global Programs",      desc: "Disburse funds internationally with compliant payment rails." },
      { icon: "Users",          title: "Beneficiary Mgmt",     desc: "Manage verified beneficiaries and track distributions." },
      { icon: "CheckSquare",    title: "Compliance Reports",   desc: "Automated compliance and grant reporting." },
      { icon: "BarChart3",      title: "Budget Tracking",      desc: "Monitor spending against program budgets." },
    ],
  },
  {
    path: "/who-we-serve/developer-portal",
    seo: { title: "Developer Portal", desc: "REST API, SDKs, and sandbox for payment integrations.", keywords: "payments API platform fintech developers" },
    tag: "WHO WE SERVE", title: "Build on Paydex",
    subtitle: "A developer-first API platform with comprehensive documentation and sandbox access.",
    features: [
      { icon: "Terminal", title: "REST API",      desc: "Clean, versioned REST API with OpenAPI specification." },
      { icon: "Code2",    title: "SDKs",          desc: "Official SDKs for Node.js, Python, PHP, Java, and Go." },
      { icon: "Database", title: "Sandbox",       desc: "Full-featured sandbox with simulated responses." },
      { icon: "Zap",      title: "Webhooks",      desc: "Real-time event notifications for payment state changes." },
      { icon: "Shield",   title: "OAuth 2.0",     desc: "Secure authentication with scoped access." },
      { icon: "BookOpen", title: "API Reference", desc: "Detailed documentation with code examples." },
    ],
  },
];
// ─── Platform Pages ───────────────────────────────────────────────────────────
export const platformPages = [
  {
    path: "/platform/security-compliance",
    seo: { title: "Security and Compliance", desc: "SOC 2 Type II, PCI DSS Level 1, GDPR-ready.", keywords: "payment security SOC2 PCI DSS fintech compliance" },
    tag: "PLATFORM", title: "Security You Can Build a Business On",
    subtitle: "SOC 2 Type II, PCI DSS Level 1, and end-to-end encryption — independently audited every year.",
    features: [
      { icon: "Shield",      title: "SOC 2 Type II",         desc: "Independently audited annually. Reports available under NDA." },
      { icon: "Lock",        title: "PCI DSS Level 1",       desc: "Highest level of payment card industry certification." },
      { icon: "Fingerprint", title: "End-to-End Encryption", desc: "AES-256 encryption at rest, TLS 1.3 in transit." },
      { icon: "Eye",         title: "24/7 Monitoring",       desc: "Dedicated security operations monitoring threats around the clock." },
      { icon: "CheckSquare", title: "GDPR Compliance",       desc: "Full data subject rights support and data processing agreements available." },
      { icon: "BarChart3",   title: "Compliance Reporting",  desc: "Automated AML, sanctions screening, and transaction monitoring reports." },
    ],
  },
  {
    path: "/platform/api-integrations",
    seo: { title: "API and Integrations", desc: "200+ pre-built connectors and developer-friendly REST API.", keywords: "payments API integrations fintech platform" },
    tag: "PLATFORM", title: "Integrate With Everything",
    subtitle: "200+ pre-built connectors and a REST API that fits into any stack — without a 6-month implementation.",
    features: [
      { icon: "Link2",    title: "200+ Connectors",    desc: "SAP, Oracle, NetSuite, Workday, QuickBooks, and more." },
      { icon: "Terminal", title: "REST API",           desc: "Versioned, documented API with webhooks and event streaming." },
      { icon: "Zap",      title: "Real-Time Webhooks", desc: "Get notified instantly when any payment status changes." },
      { icon: "Code2",    title: "SDKs",               desc: "Node.js, Python, PHP, Java, Go, and Ruby SDKs maintained by Paydex." },
      { icon: "Database", title: "Data Sync",          desc: "Bi-directional data sync with ERP and accounting platforms." },
      { icon: "Shield",   title: "Sandbox Testing",    desc: "Full sandbox environment for integration testing before go-live." },
    ],
  },
  {
    path: "/platform/global-rails",
    seo: { title: "Global Payment Rails", desc: "Pay employees and contractors across the United States and Europe with multi-currency support.", keywords: "global payments rails E-checks ACH SEPA SWIFT RTP" },
    tag: "PLATFORM", title: "Pay Anyone, Anywhere",
    subtitle: "Pay employees and contractors across the United States and Europe with multi-currency support.",
    features: [
      { icon: "Globe",      title: "Cross-Border Payouts",        desc: "Domestic and cross-border coverage across major global markets." },
      { icon: "RefreshCcw", title: "Smart Routing",         desc: "AI selects the optimal rail — digital check, FedNow, SEPA Instant, Faster Payments, or SWIFT." },
      { icon: "CreditCard", title: "FX Engine",             desc: "Competitive FX rates with transparent pricing and no hidden spreads." },
      { icon: "Zap",        title: "Real-Time Rails",       desc: "Instant payment rails supported across multiple global markets." },
      { icon: "BarChart3",  title: "FX Exposure Reporting", desc: "Monitor and hedge currency exposure across payment flows." },
      { icon: "Shield",     title: "Sanctions Screening",   desc: "OFAC, EU, and UN sanctions list screening on every transaction." },
    ],
  },
  {
    path: "/platform/fraud-prevention",
    seo: { title: "Fraud Prevention", desc: "AI-powered fraud detection for every payment.", keywords: "payment fraud detection fintech security AI" },
    tag: "PLATFORM", title: "Stop Fraud Before It Happens",
    subtitle: "AI-powered risk scoring, behavioural analysis, and real-time fraud signals on every transaction.",
    features: [
      { icon: "Lock",        title: "AI Risk Scoring",     desc: "Machine learning models score every payment for fraud risk." },
      { icon: "Eye",         title: "Behavioural Analysis",desc: "Detect anomalies in user behaviour and payment patterns." },
      { icon: "Shield",      title: "Rules Engine",        desc: "Custom fraud rules tuned to your business and risk tolerance." },
      { icon: "AlertCircle", title: "Real-Time Alerts",    desc: "Instant alerts for suspicious activity requiring review." },
      { icon: "Users",       title: "KYB / KYC",           desc: "Business and individual verification integrated into onboarding." },
      { icon: "CheckSquare", title: "Dispute Management",  desc: "Tools for investigating and resolving payment disputes." },
    ],
  },
  {
    path: "/platform/real-time-processing",
    seo: { title: "Real-Time Processing", desc: "Sub-second payment initiation and settlement.", keywords: "real time payments fintech infrastructure RTP" },
    tag: "PLATFORM", title: "Real-Time. Every Time.",
    subtitle: "Sub-second processing, instant settlement, and live status on every payment — no batches, no delays.",
    features: [
      { icon: "Zap",        title: "Sub-Second Initiation", desc: "Payments are validated and routed in under 500ms." },
      { icon: "Globe",      title: "Instant Settlement",    desc: "Real-time payment rails deliver funds within seconds where supported." },
      { icon: "BarChart3",  title: "Live Status Feed",      desc: "Real-time payment status streamed via webhooks and dashboards." },
      { icon: "RefreshCcw", title: "Auto-Retry",            desc: "Failed payments are retried automatically on the next optimal rail." },
      { icon: "Shield",     title: "99.99% Uptime SLA",     desc: "Contractual uptime guarantee backed by redundant infrastructure." },
      { icon: "Database",   title: "Redundancy",            desc: "Multi-region active-active architecture with no single point of failure." },
    ],
  },
];